language: cpp

compiler:
- gcc

os:
- linux

before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

#git:
  # Remove log info on cloning (default: false)
  #quiet: true
  # Clone git submodules (default: true)
  # submodules: false
