language: cpp

compiler:
- gcc

sudo: require

os:
- linux

#addons:
#  apt:
#    packages:
#      - libgtest-dev
#    sources:
#      - ubuntu-toolchain-r-test


#git:
  # Remove log info on cloning (default: false)
  #quiet: true
  # Clone git submodules (default: true)
  # submodules: false

      
before_install:
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull

- sudo apt-get install libgtest-dev
- cd /usr/src/gtest
- sudo env "PATH=$PATH" cmake CMakeLists.txt
- sudo env "PATH=$PATH" make
- sudo cp *.a /usr/lib
- cd -
  
script:
- cd plain_cmake
- mkdir build && cd build
- cmake ..
- make
