name: nodejs

on: [push]

jobs:
  testdocker:
    runs-on: ubuntu-latest
    container:
      image: ros:melodic
      options: --user 1001
    steps:  
    
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo apt update
        sudo apt install -y python-catkin-pkg python-rosdep python-wstool
        
    - name: test folders
      run: |
         ls -la
         ls -la /opt/
         ls -la /opt/ros
         ls -la /opt/ros/melodic
         whoami
        
    - name: build
      if: always()
      # docker entry point is in /__w/test_repo_g/YOUR_REPO_NAME
      run: |
        mkdir -p catkin_ws/src
        rosdep update
        /bin/bash /opt/ros/melodic/setup.bash
        cd catkin_ws/src 
        catkin_init_workspace
        cd ..
        ln -s ../test_node src
        catkin_make
