name: nodejs

on: [push]

jobs:
  testdocker:
    runs-on: ubuntu-latest
    container:
      image: ros:melodic
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
