name: nodejs

on: [push]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup pacakges
      run: | 
        cd node_js
        sudo npm install -g mocha chai
        sudo npm install chai
        sudo npm install -g mocha-junit-reporter
        sudo npm install mocha-junit-reporter --save-dev

    - name: Run Test
      run: | 
        cd node_js
        mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=test-results.xml

    - name: XUnit Viewer
      if: always()
      id: xunit-viewer
      uses: AutoModality/action-xunit-viewer@v1  
      with:
          results: node_js
          
    - name: Attach the report
      if: always()
      uses: actions/upload-artifact@v1
      with:
        # note: this refers to previous step name
        name: ${{ steps.xunit-viewer.outputs.report-name }}
        path: ${{ steps.xunit-viewer.outputs.report-dir }}
